### ISSUE TITLE
pixel 4 xl Android 11无法使用提示不支持机型

### ISSUE THREAD

**Issue by brownursidaeR** [E7KMbb/Fake_5G_icon#5]
pixel 4 xl Android 11无法使用提示不支持机型

System UI默认位置为/system/system_ext/priv-app/SystemUIGoogle/SystemUIGoogleapk

**Comment by E7KMbb** [comment]
是SystemUIGoogle.apk吗？

**Comment by E7KMbb** [comment]
是SystemUIGoogle.apk吗？

**Comment by brownursidaeR** [comment]
对的 输入法 漏了一个. 包名是SystemUIGoogle.apk

**Comment by brownursidaeR** [comment]
> 是SystemUIGoogle.apk吗？

对的 输入法 漏了一个. 包名是SystemUIGoogle.apk 如果还需要其他资料可以留言 我看看能否协助提供
