### ISSUE TITLE
doesn't work on redmi 4a

### ISSUE THREAD

**Issue by r3duc3** [E7KMbb/Fake_5G_icon#9]

**Comment by eksan127** [comment]
what Rom are you using?

I'm on redmi4a working fine, but I'm using AOSP rom

**Comment by r3duc3** [comment]
Im using **Redmi 4A - MIUI Global ROM** from [https://c.mi.com/oc/miuidownload/detail?device=1700319](https://c.mi.com/oc/miuidownload/detail?device=1700319)

**Comment by E7KMbb** [comment]
@r3duc3 Does not support MIUI
